### ISSUE TITLE
Compile failed with this message: error: invalid use of incomplete type ‘class QAction’

### ISSUE THREAD

**Issue by rickardm** [sjg20/paperman#22]
I wanted to compile paperman today because I have some old MAX files that need to be converted into another format. The compile initially failed with the error message:

`error: invalid use of incomplete type ‘class QAction’`

I looked around on the internet and figured this was a missing include happening in pagewidget.cpp. Attached is a patch of what I changed.

[20200617-patch.txt](https://github.com/sjg20/paperman/files/4796562/20200617-patch.txt)

After this change I was able to successfully compile paperman. I hope this helps.

Thank you for everybody for your work on this project. I'm helping somebody recover some photos that are saved as MAX files.

Today I also updated the wiki page, where it talks about installing the pre-requisites. I updated this page for the qt5 version of the dependencies. I wrote down what worked for me today.

**Comment by sjg20** [comment]
Thank you. I applied that patch.
