### ISSUE TITLE
Dropping a file into Paperman causes it to quit

### ISSUE THREAD

**Issue by bshanteau** [sjg20/paperman#6]
I compiled paperman in Linux Mint 17.1 and the gui appears, but when I try to drop a file into the files area, the program quits and drops back to the terminal.

**Comment by sglass68** [comment]
Hi,

You could file a bug in github. What do you expect it to do?

Regards,
Simon

**Comment by bshanteau** [comment]
When I use the Files program in Linux Mint 17.1 to copy and paste a max file into my paper folder, it shows up as an icon in the central area of Paperman. I would expect that the central area of Paperman would act like a file manager with each file shown as an icon and be able to use that for file management with the ability to copy and paste files into it, similar to the way PaperPort or any gui file manager acts.

Here is the terminal output I get when I try to copy and paste a max file into that central area of Paperman:

>$ ./paperman ~/Paperman/paper
lost selection 
0 
drop event, dest = -1, 3
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

>terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by bshanteau** [comment]
"You could file a bug in github." What do you mean? All I see in github is Create a New Issue. I don't see "File a Bug" anywhere.

**Comment by minakitty** [comment]
Very much zombie thread, may even be fixed, but Create a New Issue is github's version of file a bug.  It opens a thread and allows Pull Requests (proposed bug fixes) to be managed in the thread and potentially automatically pulled into the master build

**Comment by sglass68** [comment]
Confirmed that this is a bug, in that it crashes. The feature is not implemented, but should not crash!
